FROM python:3.9.19-bullseye

WORKDIR /root/

#A -  Copy over the code and any pre-requisite files to make the code work
COPY 
COPY 

# B - Ensure that the package requirements are installed (complete the command)
RUN pip install --no-cache-dir 

# C- Add in appropriate values here for room and token
ENV WEBEX_TOKEN=
ENV WEBEX_ROOM=

# D - Complete the command to run the function
CMD [ "python",  ]